[vk::constant_id(0)]
const int workgroup_size_x = 1;
[vk::constant_id(1)]
const int workgroup_size_y = 1;

[vk::constant_id(2)]
const int MODE = 0;

[vk::binding(0)]
Sampler2D<float4> img_src;
[vk::binding(1)]
RWTexture2D<float4> img_out;
[vk::binding(2)]
[format("rgba16f")]
RWTexture2D<float4> img_interm;

struct PushConstant {
    float threshold;
    float strength;
};

[vk::push_constant]
ConstantBuffer<PushConstant> pc;
