"""Code generation helper utilities."""

import datetime

from .spec import VULKAN_SPEC_VERSION


def generate_file_header(extra_comment: str = "") -> list[str]:
    """
    Generate standard header comment with timestamp.

    Args:
        extra_comment: Optional extra comment to add after the creation timestamp

    Returns:
        List of header lines
    """
    lines = [
        f"// This file was autogenerated for Vulkan {VULKAN_SPEC_VERSION}.",
        f"// Created: {datetime.datetime.now()}",
    ]
    if extra_comment:
        lines.append(f"// {extra_comment}")
    return lines


def generate_namespace_open() -> list[str]:
    """Generate namespace merian opening."""
    return [
        "",
        "namespace merian {",
        "",
    ]


def generate_namespace_close() -> list[str]:
    """Generate namespace closing."""
    return [
        "",
        "} // namespace merian",
        "",
    ]
