#pragma once

#include "merian-graph/nodes/render_ssmm/ssmm_guiding.slangh"

#ifdef __cplusplus
#else
import merian_shaders.gbuffer;
import merian_shaders.scene.scene;
import merian_shaders.utils.random;
import merian_shaders.utils.hash;
import merian_shaders.colors.colorspaces;
import merian_shaders.distributions.von_mises_fisher;
#endif

namespace merian {

struct SSMMPushConstant {
    SSMCStateAddress ssmc_prev;
    SSMCStateAddress ssmc_out;
    uint32_t frame;
    uint32_t seed;
};

} // namespace merian

#ifndef __cplusplus

[vk::push_constant] ConstantBuffer<merian::SSMMPushConstant> pc;

#endif
