#define TONEMAP_NONE                0
#define TONEMAP_CLAMP               1
#define TONEMAP_UNCHARTED_2         2
#define TONEMAP_REINHARD_EXTENDED   3
#define TONEMAP_ACES                4
#define TONEMAP_ACES_APPROX         5
#define TONEMAP_LOTTES              6

#define ALPHA_MODE_PASSTHROUGH 0
#define ALPHA_MODE_LUMINANCE 1
#define ALPHA_MODE_PERCEPTUAL_LUMINANCE 2
#define ALPHA_MODE_PERCEPTUAL_LUMINANCE_CLAMPED 3
