// This file was autogenerated for Vulkan v1.4.338.
// Created: 2026-01-28 00:28:13.121621
// Do not edit manually!

#include "merian/vk/utils/vulkan_extensions.hpp"

#include <cstring>
#include <vulkan/vulkan.h>

namespace merian {

std::vector<const char*> get_extension_dependencies(const char* name, uint32_t vk_api_version) {
    std::vector<const char*> result;

    if (std::strcmp(name, VK_AMD_ANTI_LAG_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_AMD_DEVICE_COHERENT_MEMORY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_AMD_DISPLAY_NATIVE_HDR_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME);
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_AMD_SHADER_CORE_PROPERTIES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_AMD_SHADER_CORE_PROPERTIES_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_AMD_SHADER_CORE_PROPERTIES_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_AMD_SHADER_EARLY_AND_LATE_FRAGMENT_TESTS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_AMD_TEXTURE_GATHER_BIAS_LOD_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_ARM_DATA_GRAPH_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_MAINTENANCE_5_EXTENSION_NAME);
        result.push_back(VK_KHR_DEFERRED_HOST_OPERATIONS_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_ARM_FORMAT_PACK_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_ARM_PERFORMANCE_COUNTERS_BY_REGION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_ARM_PIPELINE_OPACITY_MICROMAP_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_OPACITY_MICROMAP_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_ARM_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_ARM_RENDER_PASS_STRIPED_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_ARM_SCHEDULING_CONTROLS_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_ARM_SHADER_CORE_BUILTINS_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_ARM_SHADER_CORE_BUILTINS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_ARM_SHADER_CORE_PROPERTIES_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_ARM_TENSORS_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_EXT_4444_FORMATS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_ACQUIRE_DRM_DISPLAY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_DIRECT_MODE_DISPLAY_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_ASTC_DECODE_MODE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_ATTACHMENT_FEEDBACK_LOOP_DYNAMIC_STATE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_ATTACHMENT_FEEDBACK_LOOP_LAYOUT_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_ATTACHMENT_FEEDBACK_LOOP_LAYOUT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_BLEND_OPERATION_ADVANCED_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_BORDER_COLOR_SWIZZLE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_CUSTOM_BORDER_COLOR_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_CALIBRATED_TIMESTAMPS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_COLOR_WRITE_ENABLE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_CONDITIONAL_RENDERING_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_CONSERVATIVE_RASTERIZATION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_CUSTOM_BORDER_COLOR_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_CUSTOM_RESOLVE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DEBUG_MARKER_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_DEBUG_REPORT_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_DEPTH_BIAS_CONTROL_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DEPTH_CLAMP_CONTROL_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DEPTH_CLAMP_ZERO_ONE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DEPTH_CLIP_CONTROL_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DEPTH_CLIP_ENABLE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DESCRIPTOR_BUFFER_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME);
            result.push_back(VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
            result.push_back(VK_KHR_MAINTENANCE_3_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DEVICE_ADDRESS_BINDING_REPORT_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_DEBUG_UTILS_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_DEVICE_FAULT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_MAINTENANCE_5_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DEVICE_MEMORY_REPORT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DIRECT_MODE_DISPLAY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_DISPLAY_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_DISCARD_RECTANGLES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_DISPLAY_CONTROL_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_DISPLAY_SURFACE_COUNTER_EXTENSION_NAME);
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_DISPLAY_SURFACE_COUNTER_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_DISPLAY_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_DYNAMIC_RENDERING_UNUSED_ATTACHMENTS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_EXTENDED_DYNAMIC_STATE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_EXTENDED_DYNAMIC_STATE_2_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_EXTENDED_DYNAMIC_STATE_3_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_EXTERNAL_MEMORY_ACQUIRE_UNMODIFIED_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_EXTERNAL_MEMORY_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_EXTERNAL_MEMORY_DMA_BUF_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_EXTERNAL_MEMORY_FD_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_EXTERNAL_MEMORY_HOST_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_EXTERNAL_MEMORY_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_FRAGMENT_DENSITY_MAP_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_FRAGMENT_DENSITY_MAP_OFFSET_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_FRAGMENT_SHADER_INTERLOCK_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_FRAME_BOUNDARY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_GLOBAL_PRIORITY_QUERY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_GLOBAL_PRIORITY_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_GRAPHICS_PIPELINE_LIBRARY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_PIPELINE_LIBRARY_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_HDR_METADATA_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_HEADLESS_SURFACE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_HOST_IMAGE_COPY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_COPY_COMMANDS_2_EXTENSION_NAME);
            result.push_back(VK_KHR_FORMAT_FEATURE_FLAGS_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_HOST_QUERY_RESET_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_IMAGE_2D_VIEW_OF_3D_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_MAINTENANCE_1_EXTENSION_NAME);
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_IMAGE_COMPRESSION_CONTROL_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_IMAGE_COMPRESSION_CONTROL_SWAPCHAIN_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_IMAGE_COMPRESSION_CONTROL_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_IMAGE_DRM_FORMAT_MODIFIER_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_BIND_MEMORY_2_EXTENSION_NAME);
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
            result.push_back(VK_KHR_IMAGE_FORMAT_LIST_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_IMAGE_ROBUSTNESS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_IMAGE_SLICED_VIEW_OF_3D_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_MAINTENANCE_1_EXTENSION_NAME);
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_IMAGE_VIEW_MIN_LOD_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_INDEX_TYPE_UINT8_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_INLINE_UNIFORM_BLOCK_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
            result.push_back(VK_KHR_MAINTENANCE_1_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_LEGACY_DITHERING_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_LEGACY_VERTEX_ATTRIBUTES_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_VERTEX_INPUT_DYNAMIC_STATE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_LINE_RASTERIZATION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_MAP_MEMORY_PLACED_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_4) {
            result.push_back(VK_KHR_MAP_MEMORY_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_MEMORY_BUDGET_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_MEMORY_DECOMPRESSION_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        result.push_back(VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_MEMORY_PRIORITY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_MESH_SHADER_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_SPIRV_1_4_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_MULTI_DRAW_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_CREATE_RENDERPASS_2_EXTENSION_NAME);
            result.push_back(VK_KHR_DEPTH_STENCIL_RESOLVE_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_MUTABLE_DESCRIPTOR_TYPE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_MAINTENANCE_3_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_NESTED_COMMAND_BUFFER_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_NON_SEAMLESS_CUBE_MAP_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_OPACITY_MICROMAP_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_PAGEABLE_DEVICE_LOCAL_MEMORY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_MEMORY_PRIORITY_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_PCI_BUS_INFO_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_PHYSICAL_DEVICE_DRM_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_PIPELINE_CREATION_CACHE_CONTROL_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_PIPELINE_LIBRARY_GROUP_HANDLES_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME);
        result.push_back(VK_KHR_PIPELINE_LIBRARY_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_PIPELINE_PROPERTIES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_PIPELINE_PROTECTED_ACCESS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_PIPELINE_ROBUSTNESS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_PRESENT_MODE_FIFO_LATEST_READY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_PRESENT_TIMING_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
        result.push_back(VK_KHR_PRESENT_ID_2_EXTENSION_NAME);
        result.push_back(VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME);
        result.push_back(VK_KHR_CALIBRATED_TIMESTAMPS_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_PRIMITIVE_TOPOLOGY_LIST_RESTART_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_PRIMITIVES_GENERATED_QUERY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_PRIVATE_DATA_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_PROVOKING_VERTEX_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_QUEUE_FAMILY_FOREIGN_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_EXTERNAL_MEMORY_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_RGBA10X6_FORMATS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_ROBUSTNESS_2_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SAMPLE_LOCATIONS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SAMPLER_FILTER_MINMAX_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SCALAR_BLOCK_LAYOUT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SHADER_64BIT_INDEXING_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SHADER_ATOMIC_FLOAT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SHADER_ATOMIC_FLOAT_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_SHADER_ATOMIC_FLOAT_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_SHADER_DEMOTE_TO_HELPER_INVOCATION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SHADER_FLOAT8_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SHADER_IMAGE_ATOMIC_INT64_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SHADER_LONG_VECTOR_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_EXT_SHADER_MODULE_IDENTIFIER_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_EXT_PIPELINE_CREATION_CACHE_CONTROL_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SHADER_OBJECT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SHADER_REPLICATED_COMPOSITES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SHADER_TILE_IMAGE_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_EXT_SHADER_UNIFORM_BUFFER_UNSIZED_ARRAY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SUBGROUP_SIZE_CONTROL_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_EXT_SUBPASS_MERGE_FEEDBACK_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_SURFACE_MAINTENANCE_1_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
        result.push_back(VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_SWAPCHAIN_COLOR_SPACE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_SWAPCHAIN_MAINTENANCE_1_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
        result.push_back(VK_EXT_SURFACE_MAINTENANCE_1_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_EXT_TEXEL_BUFFER_ALIGNMENT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_TEXTURE_COMPRESSION_ASTC_3D_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_TEXTURE_COMPRESSION_ASTC_HDR_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_VERTEX_ATTRIBUTE_DIVISOR_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_VERTEX_ATTRIBUTE_ROBUSTNESS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_VERTEX_INPUT_DYNAMIC_STATE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_YCBCR_2PLANE_444_FORMATS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_YCBCR_IMAGE_ARRAYS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_EXT_ZERO_INITIALIZE_DEVICE_MEMORY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_GOOGLE_DISPLAY_TIMING_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_GOOGLE_SURFACELESS_QUERY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_HUAWEI_CLUSTER_CULLING_SHADER_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_HUAWEI_HDR_VIVID_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
        result.push_back(VK_EXT_HDR_METADATA_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_HUAWEI_INVOCATION_MASK_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_HUAWEI_SUBPASS_SHADING_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_IMG_RELAXED_LINE_RASTERIZATION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_INTEL_SHADER_INTEGER_FUNCTIONS_2_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_16BIT_STORAGE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
            result.push_back(VK_KHR_STORAGE_BUFFER_STORAGE_CLASS_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_8BIT_STORAGE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
            result.push_back(VK_KHR_STORAGE_BUFFER_STORAGE_CLASS_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME);
        result.push_back(VK_KHR_DEFERRED_HOST_OPERATIONS_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
            result.push_back(VK_KHR_DEVICE_GROUP_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_CALIBRATED_TIMESTAMPS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_COMPUTE_SHADER_DERIVATIVES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_COOPERATIVE_MATRIX_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_COPY_COMMANDS_2_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_COPY_MEMORY_INDIRECT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
            result.push_back(VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_CREATE_RENDERPASS_2_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_MULTIVIEW_EXTENSION_NAME);
            result.push_back(VK_KHR_MAINTENANCE_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_DEDICATED_ALLOCATION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_DEPTH_CLAMP_ZERO_ONE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_DEPTH_STENCIL_RESOLVE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_CREATE_RENDERPASS_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_DEVICE_GROUP_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_DEVICE_GROUP_CREATION_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_DISPLAY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_DISPLAY_SWAPCHAIN_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
        result.push_back(VK_KHR_DISPLAY_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_DRIVER_PROPERTIES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_DEPTH_STENCIL_RESOLVE_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_DYNAMIC_RENDERING_LOCAL_READ_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_EXTERNAL_FENCE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_EXTERNAL_FENCE_CAPABILITIES_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_EXTERNAL_FENCE_CAPABILITIES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_EXTERNAL_FENCE_FD_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_EXTERNAL_FENCE_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_EXTERNAL_MEMORY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_EXTERNAL_MEMORY_CAPABILITIES_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_EXTERNAL_MEMORY_CAPABILITIES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_EXTERNAL_MEMORY_FD_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_EXTERNAL_MEMORY_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_EXTERNAL_SEMAPHORE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_EXTERNAL_SEMAPHORE_CAPABILITIES_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_EXTERNAL_SEMAPHORE_CAPABILITIES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_EXTERNAL_SEMAPHORE_FD_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_EXTERNAL_SEMAPHORE_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_FORMAT_FEATURE_FLAGS_2_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_FRAGMENT_SHADER_BARYCENTRIC_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_FRAGMENT_SHADING_RATE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_CREATE_RENDERPASS_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_GET_DISPLAY_PROPERTIES_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_DISPLAY_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_GLOBAL_PRIORITY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_IMAGELESS_FRAMEBUFFER_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
            result.push_back(VK_KHR_IMAGE_FORMAT_LIST_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_INCREMENTAL_PRESENT_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_INDEX_TYPE_UINT8_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_LINE_RASTERIZATION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_MAINTENANCE_10_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_MAINTENANCE_3_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_MAINTENANCE_4_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_KHR_MAINTENANCE_5_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_MAINTENANCE_6_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_KHR_MAINTENANCE_7_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_KHR_MAINTENANCE_8_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_KHR_MAINTENANCE_9_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_MULTIVIEW_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_PERFORMANCE_QUERY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_PIPELINE_BINARY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_4) {
            result.push_back(VK_KHR_MAINTENANCE_5_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_PIPELINE_EXECUTABLE_PROPERTIES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_PRESENT_ID_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_PRESENT_ID_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME);
        result.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_PRESENT_MODE_FIFO_LATEST_READY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_PRESENT_WAIT_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
        result.push_back(VK_KHR_PRESENT_ID_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_PRESENT_WAIT_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME);
        result.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
        result.push_back(VK_KHR_PRESENT_ID_2_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_PUSH_DESCRIPTOR_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_RAY_QUERY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_RAY_TRACING_MAINTENANCE_1_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_RAY_TRACING_POSITION_FETCH_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_ROBUSTNESS_2_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_MAINTENANCE_1_EXTENSION_NAME);
            result.push_back(VK_KHR_BIND_MEMORY_2_EXTENSION_NAME);
            result.push_back(VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION_NAME);
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SEPARATE_DEPTH_STENCIL_LAYOUTS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_CREATE_RENDERPASS_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_ATOMIC_INT64_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_BFLOAT16_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_CLOCK_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_EXPECT_ASSUME_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_FLOAT16_INT8_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_FLOAT_CONTROLS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_FLOAT_CONTROLS_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SHADER_FLOAT_CONTROLS_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_SHADER_FMA_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_INTEGER_DOT_PRODUCT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_MAXIMAL_RECONVERGENCE_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_KHR_SHADER_QUAD_CONTROL_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SHADER_MAXIMAL_RECONVERGENCE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_SHADER_RELAXED_EXTENDED_INSTRUCTION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_SUBGROUP_EXTENDED_TYPES_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_KHR_SHADER_SUBGROUP_ROTATE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_SUBGROUP_UNIFORM_CONTROL_FLOW_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_KHR_SHADER_TERMINATE_INVOCATION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_SHADER_UNTYPED_POINTERS_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_SHARED_PRESENTABLE_IMAGE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
        result.push_back(VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_SPIRV_1_4_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SHADER_FLOAT_CONTROLS_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_SURFACE_MAINTENANCE_1_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_SURFACE_PROTECTED_CAPABILITIES_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_SWAPCHAIN_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_SWAPCHAIN_MAINTENANCE_1_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_SWAPCHAIN_MUTABLE_FORMAT_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_TIMELINE_SEMAPHORE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_UNIFIED_IMAGE_LAYOUTS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_UNIFORM_BUFFER_STANDARD_LAYOUT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_VARIABLE_POINTERS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
            result.push_back(VK_KHR_STORAGE_BUFFER_STORAGE_CLASS_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_VERTEX_ATTRIBUTE_DIVISOR_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_VIDEO_DECODE_AV1_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_DECODE_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_DECODE_H264_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_DECODE_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_DECODE_H265_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_DECODE_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_DECODE_QUEUE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_DECODE_VP9_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_DECODE_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_ENCODE_AV1_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_ENCODE_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_ENCODE_H264_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_ENCODE_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_ENCODE_H265_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_ENCODE_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_ENCODE_INTRA_REFRESH_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_ENCODE_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_ENCODE_QUANTIZATION_MAP_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_ENCODE_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_ENCODE_QUEUE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_MAINTENANCE_1_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_MAINTENANCE_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_QUEUE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_KHR_VIDEO_QUEUE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_VULKAN_MEMORY_MODEL_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_WORKGROUP_MEMORY_EXPLICIT_LAYOUT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_KHR_ZERO_INITIALIZE_WORKGROUP_MEMORY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_MESA_IMAGE_ALIGNMENT_CONTROL_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_MSFT_LAYERED_DRIVER_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NVX_MULTIVIEW_PER_VIEW_ATTRIBUTES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_MULTIVIEW_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_COMMAND_BUFFER_INHERITANCE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_COMPUTE_OCCUPANCY_PRIORITY_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_COMPUTE_SHADER_DERIVATIVES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_COOPERATIVE_MATRIX_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_COOPERATIVE_MATRIX_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_COOPERATIVE_VECTOR_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_COPY_MEMORY_INDIRECT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_CORNER_SAMPLED_IMAGE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_COVERAGE_REDUCTION_MODE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_NV_FRAMEBUFFER_MIXED_SAMPLES_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_DEDICATED_ALLOCATION_IMAGE_ALIASING_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_DEDICATED_ALLOCATION_EXTENSION_NAME);
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_DESCRIPTOR_POOL_OVERALLOCATION_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_NV_DEVICE_DIAGNOSTIC_CHECKPOINTS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_DEVICE_DIAGNOSTICS_CONFIG_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_DEVICE_GENERATED_COMMANDS_COMPUTE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_NV_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_DISPLAY_STEREO_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_DISPLAY_EXTENSION_NAME);
        result.push_back(VK_KHR_GET_DISPLAY_PROPERTIES_2_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_EXTENDED_SPARSE_ADDRESS_SPACE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_EXTERNAL_MEMORY_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_NV_EXTERNAL_MEMORY_CAPABILITIES_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_EXTERNAL_MEMORY_RDMA_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_EXTERNAL_MEMORY_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_FRAGMENT_SHADER_BARYCENTRIC_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_FRAGMENT_SHADING_RATE_ENUMS_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_FRAGMENT_SHADING_RATE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_INHERITED_VIEWPORT_SCISSOR_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_LINEAR_COLOR_ATTACHMENT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_LOW_LATENCY_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_NV_MEMORY_DECOMPRESSION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_2) {
            result.push_back(VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_MESH_SHADER_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_OPTICAL_FLOW_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_FORMAT_FEATURE_FLAGS_2_EXTENSION_NAME);
            result.push_back(VK_KHR_SYNCHRONIZATION_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_PER_STAGE_DESCRIPTOR_SET_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_4) {
            result.push_back(VK_KHR_MAINTENANCE_6_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_PRESENT_BARRIER_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_SURFACE_EXTENSION_NAME);
        result.push_back(VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME);
        result.push_back(VK_KHR_SWAPCHAIN_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_RAW_ACCESS_CHAINS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_RAY_TRACING_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
            result.push_back(VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_RAY_TRACING_LINEAR_SWEPT_SPHERES_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_RAY_TRACING_MOTION_BLUR_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_NV_RAY_TRACING_VALIDATION_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_REPRESENTATIVE_FRAGMENT_TEST_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_SCISSOR_EXCLUSIVE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_SHADER_ATOMIC_FLOAT16_VECTOR_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_SHADER_IMAGE_FOOTPRINT_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_NV_SHADER_SM_BUILTINS_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_NV_SHADER_SUBGROUP_PARTITIONED_EXTENSION_NAME) == 0) {
        (void)vk_api_version; // Satisfied by Vulkan version
    } else if (std::strcmp(name, VK_NV_SHADING_RATE_IMAGE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_QCOM_DATA_GRAPH_MODEL_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_ARM_DATA_GRAPH_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_QCOM_FILTER_CUBIC_CLAMP_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_FILTER_CUBIC_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_QCOM_FILTER_CUBIC_WEIGHTS_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_FILTER_CUBIC_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_QCOM_FRAGMENT_DENSITY_MAP_OFFSET_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_QCOM_IMAGE_PROCESSING_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_FORMAT_FEATURE_FLAGS_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_QCOM_IMAGE_PROCESSING_2_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_QCOM_IMAGE_PROCESSING_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_QCOM_MULTIVIEW_PER_VIEW_RENDER_AREAS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_QCOM_MULTIVIEW_PER_VIEW_VIEWPORTS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_QCOM_ROTATED_COPY_COMMANDS_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_3) {
            result.push_back(VK_KHR_COPY_COMMANDS_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_QCOM_TILE_MEMORY_HEAP_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_MEMORY_REQUIREMENTS_2_EXTENSION_NAME);
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_QCOM_TILE_PROPERTIES_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_QCOM_TILE_SHADING_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_QCOM_TILE_PROPERTIES_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_QCOM_YCBCR_DEGAMMA_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_SEC_AMIGO_PROFILING_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_SEC_PIPELINE_CACHE_INCREMENTAL_MODE_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_VALVE_DESCRIPTOR_SET_HOST_MAPPING_EXTENSION_NAME) == 0) {
        if (vk_api_version < VK_API_VERSION_1_1) {
            result.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
        }
    } else if (std::strcmp(name, VK_VALVE_FRAGMENT_DENSITY_MAP_LAYERED_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_VALVE_MUTABLE_DESCRIPTOR_TYPE_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_MAINTENANCE_3_EXTENSION_NAME);
    } else if (std::strcmp(name, VK_VALVE_VIDEO_ENCODE_RGB_CONVERSION_EXTENSION_NAME) == 0) {
        (void)vk_api_version;
        result.push_back(VK_KHR_VIDEO_ENCODE_QUEUE_EXTENSION_NAME);
    }

    return result;
}

std::vector<vk::StructureType> get_extension_property_types(const char* name) {
    std::vector<vk::StructureType> result;

    if (std::strcmp(name, VK_AMD_SHADER_CORE_PROPERTIES_2_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceShaderCoreProperties2Amd);
    } else if (std::strcmp(name, VK_AMD_SHADER_CORE_PROPERTIES_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceShaderCorePropertiesAmd);
    } else if (std::strcmp(name, VK_ARM_PERFORMANCE_COUNTERS_BY_REGION_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDevicePerformanceCountersByRegionPropertiesArm);
    } else if (std::strcmp(name, VK_ARM_RENDER_PASS_STRIPED_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceRenderPassStripedPropertiesArm);
    } else if (std::strcmp(name, VK_ARM_SCHEDULING_CONTROLS_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceSchedulingControlsPropertiesArm);
    } else if (std::strcmp(name, VK_ARM_SHADER_CORE_BUILTINS_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceShaderCoreBuiltinsPropertiesArm);
    } else if (std::strcmp(name, VK_ARM_SHADER_CORE_PROPERTIES_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceShaderCorePropertiesArm);
    } else if (std::strcmp(name, VK_ARM_TENSORS_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceDescriptorBufferTensorPropertiesArm);
        result.push_back(vk::StructureType::ePhysicalDeviceTensorPropertiesArm);
    } else if (std::strcmp(name, VK_EXT_BLEND_OPERATION_ADVANCED_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceBlendOperationAdvancedPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_CONSERVATIVE_RASTERIZATION_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceConservativeRasterizationPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_CUSTOM_BORDER_COLOR_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceCustomBorderColorPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_DESCRIPTOR_BUFFER_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceDescriptorBufferDensityMapPropertiesExt);
        result.push_back(vk::StructureType::ePhysicalDeviceDescriptorBufferPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceDeviceGeneratedCommandsPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_DISCARD_RECTANGLES_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceDiscardRectanglePropertiesExt);
    } else if (std::strcmp(name, VK_EXT_EXTENDED_DYNAMIC_STATE_3_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceExtendedDynamicState3PropertiesExt);
    } else if (std::strcmp(name, VK_EXT_EXTERNAL_MEMORY_HOST_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceExternalMemoryHostPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_FRAGMENT_DENSITY_MAP_2_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceFragmentDensityMap2PropertiesExt);
    } else if (std::strcmp(name, VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceFragmentDensityMapPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_FRAGMENT_DENSITY_MAP_OFFSET_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceFragmentDensityMapOffsetPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_GRAPHICS_PIPELINE_LIBRARY_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceGraphicsPipelineLibraryPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_LEGACY_VERTEX_ATTRIBUTES_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceLegacyVertexAttributesPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_MAP_MEMORY_PLACED_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceMapMemoryPlacedPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_MEMORY_DECOMPRESSION_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceMemoryDecompressionPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_MESH_SHADER_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceMeshShaderPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_MULTI_DRAW_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceMultiDrawPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_NESTED_COMMAND_BUFFER_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceNestedCommandBufferPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_OPACITY_MICROMAP_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceOpacityMicromapPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_PCI_BUS_INFO_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDevicePciBusInfoPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_PHYSICAL_DEVICE_DRM_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceDrmPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_PROVOKING_VERTEX_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceProvokingVertexPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceRayTracingInvocationReorderPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_SAMPLE_LOCATIONS_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceSampleLocationsPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_SHADER_LONG_VECTOR_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceShaderLongVectorPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_SHADER_MODULE_IDENTIFIER_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceShaderModuleIdentifierPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_SHADER_OBJECT_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceShaderObjectPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_SHADER_TILE_IMAGE_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceShaderTileImagePropertiesExt);
    } else if (std::strcmp(name, VK_EXT_TRANSFORM_FEEDBACK_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceTransformFeedbackPropertiesExt);
    } else if (std::strcmp(name, VK_EXT_VERTEX_ATTRIBUTE_DIVISOR_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceVertexAttributeDivisorPropertiesExt);
    } else if (std::strcmp(name, VK_HUAWEI_CLUSTER_CULLING_SHADER_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceClusterCullingShaderPropertiesHuawei);
    } else if (std::strcmp(name, VK_HUAWEI_SUBPASS_SHADING_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceSubpassShadingPropertiesHuawei);
    } else if (std::strcmp(name, VK_KHR_ACCELERATION_STRUCTURE_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceAccelerationStructurePropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_COMPUTE_SHADER_DERIVATIVES_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceComputeShaderDerivativesPropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_COOPERATIVE_MATRIX_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceCooperativeMatrixPropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_COPY_MEMORY_INDIRECT_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceCopyMemoryIndirectPropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_FRAGMENT_SHADER_BARYCENTRIC_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceFragmentShaderBarycentricPropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_FRAGMENT_SHADING_RATE_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceFragmentShadingRatePropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_MAINTENANCE_10_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceMaintenance10PropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_MAINTENANCE_7_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceLayeredApiPropertiesListKhr);
        result.push_back(vk::StructureType::ePhysicalDeviceMaintenance7PropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_MAINTENANCE_9_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceMaintenance9PropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_PERFORMANCE_QUERY_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDevicePerformanceQueryPropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_PIPELINE_BINARY_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDevicePipelineBinaryPropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_RAY_TRACING_PIPELINE_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceRayTracingPipelinePropertiesKhr);
    } else if (std::strcmp(name, VK_KHR_ROBUSTNESS_2_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceRobustness2PropertiesKhr);
    } else if (std::strcmp(name, VK_MESA_IMAGE_ALIGNMENT_CONTROL_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceImageAlignmentControlPropertiesMesa);
    } else if (std::strcmp(name, VK_MSFT_LAYERED_DRIVER_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceLayeredDriverPropertiesMsft);
    } else if (std::strcmp(name, VK_NVX_MULTIVIEW_PER_VIEW_ATTRIBUTES_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceMultiviewPerViewAttributesPropertiesNvx);
    } else if (std::strcmp(name, VK_NV_CLUSTER_ACCELERATION_STRUCTURE_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceClusterAccelerationStructurePropertiesNv);
    } else if (std::strcmp(name, VK_NV_COOPERATIVE_MATRIX_2_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceCooperativeMatrix2PropertiesNv);
    } else if (std::strcmp(name, VK_NV_COOPERATIVE_MATRIX_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceCooperativeMatrixPropertiesNv);
    } else if (std::strcmp(name, VK_NV_COOPERATIVE_VECTOR_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceCooperativeVectorPropertiesNv);
    } else if (std::strcmp(name, VK_NV_DEVICE_GENERATED_COMMANDS_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceDeviceGeneratedCommandsPropertiesNv);
    } else if (std::strcmp(name, VK_NV_EXTENDED_SPARSE_ADDRESS_SPACE_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceExtendedSparseAddressSpacePropertiesNv);
    } else if (std::strcmp(name, VK_NV_EXTERNAL_COMPUTE_QUEUE_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceExternalComputeQueuePropertiesNv);
    } else if (std::strcmp(name, VK_NV_FRAGMENT_SHADING_RATE_ENUMS_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceFragmentShadingRateEnumsPropertiesNv);
    } else if (std::strcmp(name, VK_NV_MESH_SHADER_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceMeshShaderPropertiesNv);
    } else if (std::strcmp(name, VK_NV_OPTICAL_FLOW_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceOpticalFlowPropertiesNv);
    } else if (std::strcmp(name, VK_NV_PARTITIONED_ACCELERATION_STRUCTURE_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDevicePartitionedAccelerationStructurePropertiesNv);
    } else if (std::strcmp(name, VK_NV_RAY_TRACING_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceRayTracingPropertiesNv);
    } else if (std::strcmp(name, VK_NV_RAY_TRACING_INVOCATION_REORDER_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceRayTracingInvocationReorderPropertiesNv);
    } else if (std::strcmp(name, VK_NV_SHADER_SM_BUILTINS_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceShaderSmBuiltinsPropertiesNv);
    } else if (std::strcmp(name, VK_NV_SHADING_RATE_IMAGE_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceShadingRateImagePropertiesNv);
    } else if (std::strcmp(name, VK_QCOM_IMAGE_PROCESSING_2_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceImageProcessing2PropertiesQcom);
    } else if (std::strcmp(name, VK_QCOM_IMAGE_PROCESSING_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceImageProcessingPropertiesQcom);
    } else if (std::strcmp(name, VK_QCOM_TILE_MEMORY_HEAP_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceTileMemoryHeapPropertiesQcom);
    } else if (std::strcmp(name, VK_QCOM_TILE_SHADING_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceTileShadingPropertiesQcom);
    } else if (std::strcmp(name, VK_VALVE_FRAGMENT_DENSITY_MAP_LAYERED_EXTENSION_NAME) == 0) {
        result.push_back(vk::StructureType::ePhysicalDeviceFragmentDensityMapLayeredPropertiesValve);
    }

    return result;
}

std::vector<vk::StructureType> get_api_version_property_types(uint32_t vk_api_version) {
    std::vector<vk::StructureType> result;

    if (vk_api_version >= VK_API_VERSION_1_1) {
        result.push_back(vk::StructureType::ePhysicalDeviceIdProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceMaintenance3Properties);
        result.push_back(vk::StructureType::ePhysicalDeviceMultiviewProperties);
        result.push_back(vk::StructureType::ePhysicalDevicePointClippingProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceProperties2);
        result.push_back(vk::StructureType::ePhysicalDeviceProtectedMemoryProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceSubgroupProperties);
    }
    if (vk_api_version >= VK_API_VERSION_1_2) {
        result.push_back(vk::StructureType::ePhysicalDeviceDepthStencilResolveProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceDescriptorIndexingProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceDriverProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceFloatControlsProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceSamplerFilterMinmaxProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceTimelineSemaphoreProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceVulkan11Properties);
        result.push_back(vk::StructureType::ePhysicalDeviceVulkan12Properties);
    }
    if (vk_api_version >= VK_API_VERSION_1_3) {
        result.push_back(vk::StructureType::ePhysicalDeviceInlineUniformBlockProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceMaintenance4Properties);
        result.push_back(vk::StructureType::ePhysicalDeviceShaderIntegerDotProductProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceSubgroupSizeControlProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceTexelBufferAlignmentProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceVulkan13Properties);
    }
    if (vk_api_version >= VK_API_VERSION_1_4) {
        result.push_back(vk::StructureType::ePhysicalDeviceHostImageCopyProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceLineRasterizationProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceMaintenance5Properties);
        result.push_back(vk::StructureType::ePhysicalDeviceMaintenance6Properties);
        result.push_back(vk::StructureType::ePhysicalDevicePipelineRobustnessProperties);
        result.push_back(vk::StructureType::ePhysicalDevicePushDescriptorProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceVertexAttributeDivisorProperties);
        result.push_back(vk::StructureType::ePhysicalDeviceVulkan14Properties);
    }

    return result;
}

} // namespace merian
