// This file was autogenerated for Vulkan v1.4.338.
// Created: 2026-01-25 21:39:19.546465
// Do not edit manually!

#pragma once

#include "vulkan/vulkan.hpp"

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace merian {

/**
 * @brief Base class for Vulkan feature structures.
 *
 * Provides a uniform interface for querying and enabling Vulkan features.
 * Each derived class wraps a specific VkPhysicalDevice*Features* structure.
 */
class Feature {
  public:
    virtual ~Feature() = default;

    /**
     * @brief Get the list of device extensions required for this feature.
     * @param vk_api_version The Vulkan API version being used.
     * @return Vector of extension name strings (may be empty for core features).
     */
    virtual std::vector<const char*> get_required_extensions(uint32_t vk_api_version) const = 0;

    /**
     * @brief Get the names of all boolean features in this structure.
     * @return Vector of feature name strings.
     */
    virtual std::vector<const char*> get_feature_names() const = 0;

    /**
     * @brief Get the value of a specific feature by name.
     * @param name The name of the feature.
     * @return The feature value, or false if not found.
     */
    virtual bool get_feature(const std::string& name) const = 0;

    /**
     * @brief Set the value of a specific feature by name.
     * @param name The name of the feature.
     * @param value The value to set.
     * @return True if the feature was found and set, false otherwise.
     */
    virtual bool set_feature(const std::string& name, bool value) = 0;

    /**
     * @brief Get the human-readable name of this feature structure.
     * @return The feature structure name.
     */
    virtual const char* get_name() const = 0;

    /**
     * @brief Get the Vulkan structure type for this feature.
     * @return The vk::StructureType enum value.
     */
    virtual vk::StructureType get_structure_type() const = 0;

    /**
     * @brief Get a pointer to the underlying Vulkan structure (for pNext chaining).
     * @return Void pointer to the feature structure.
     */
    virtual void* get_structure_ptr() = 0;

    /**
     * @brief Set the pNext pointer of the underlying structure.
     * @param p_next The pNext pointer to set.
     */
    virtual void set_pnext(void* p_next) = 0;
};

using FeatureHandle = std::shared_ptr<Feature>;

/**
 * @brief Get a Feature instance by Vulkan structure type.
 * @param stype The vk::StructureType of the feature.
 * @return A shared pointer to the Feature, or nullptr if not found.
 */
FeatureHandle get_feature(vk::StructureType stype);

/**
 * @brief Get a Feature instance by name.
 * @param name The name of the feature structure (e.g., "PhysicalDeviceRobustness2FeaturesEXT").
 * @return A shared pointer to the Feature, or nullptr if not found.
 */
FeatureHandle get_feature(const std::string& name);

// Forward declarations for feature classes
class FeaturePhysicalDevice16BitStorage;
class FeaturePhysicalDevice4444FormatsEXT;
class FeaturePhysicalDevice8BitStorage;
class FeaturePhysicalDeviceASTCDecodeEXT;
class FeaturePhysicalDeviceAccelerationStructureKHR;
class FeaturePhysicalDeviceAddressBindingReportEXT;
class FeaturePhysicalDeviceAmigoProfilingSEC;
class FeaturePhysicalDeviceAntiLagAMD;
class FeaturePhysicalDeviceAttachmentFeedbackLoopDynamicStateEXT;
class FeaturePhysicalDeviceAttachmentFeedbackLoopLayoutEXT;
class FeaturePhysicalDeviceBlendOperationAdvancedEXT;
class FeaturePhysicalDeviceBorderColorSwizzleEXT;
class FeaturePhysicalDeviceBufferDeviceAddress;
class FeaturePhysicalDeviceBufferDeviceAddressEXT;
class FeaturePhysicalDeviceClusterAccelerationStructureNV;
class FeaturePhysicalDeviceClusterCullingShaderHUAWEI;
class FeaturePhysicalDeviceCoherentMemoryAMD;
class FeaturePhysicalDeviceColorWriteEnableEXT;
class FeaturePhysicalDeviceCommandBufferInheritanceNV;
class FeaturePhysicalDeviceComputeOccupancyPriorityNV;
class FeaturePhysicalDeviceComputeShaderDerivativesKHR;
class FeaturePhysicalDeviceConditionalRenderingEXT;
class FeaturePhysicalDeviceCooperativeMatrix2NV;
class FeaturePhysicalDeviceCooperativeMatrixKHR;
class FeaturePhysicalDeviceCooperativeMatrixNV;
class FeaturePhysicalDeviceCooperativeVectorNV;
class FeaturePhysicalDeviceCopyMemoryIndirectKHR;
class FeaturePhysicalDeviceCopyMemoryIndirectNV;
class FeaturePhysicalDeviceCornerSampledImageNV;
class FeaturePhysicalDeviceCoverageReductionModeNV;
class FeaturePhysicalDeviceCubicClampQCOM;
class FeaturePhysicalDeviceCubicWeightsQCOM;
class FeaturePhysicalDeviceCustomBorderColorEXT;
class FeaturePhysicalDeviceCustomResolveEXT;
class FeaturePhysicalDeviceDataGraphARM;
class FeaturePhysicalDeviceDataGraphModelQCOM;
class FeaturePhysicalDeviceDedicatedAllocationImageAliasingNV;
class FeaturePhysicalDeviceDepthBiasControlEXT;
class FeaturePhysicalDeviceDepthClampControlEXT;
class FeaturePhysicalDeviceDepthClampZeroOneKHR;
class FeaturePhysicalDeviceDepthClipControlEXT;
class FeaturePhysicalDeviceDepthClipEnableEXT;
class FeaturePhysicalDeviceDescriptorBufferEXT;
class FeaturePhysicalDeviceDescriptorBufferTensorARM;
class FeaturePhysicalDeviceDescriptorIndexing;
class FeaturePhysicalDeviceDescriptorPoolOverallocationNV;
class FeaturePhysicalDeviceDescriptorSetHostMappingVALVE;
class FeaturePhysicalDeviceDeviceGeneratedCommandsComputeNV;
class FeaturePhysicalDeviceDeviceGeneratedCommandsEXT;
class FeaturePhysicalDeviceDeviceGeneratedCommandsNV;
class FeaturePhysicalDeviceDeviceMemoryReportEXT;
class FeaturePhysicalDeviceDiagnosticsConfigNV;
class FeaturePhysicalDeviceDynamicRendering;
class FeaturePhysicalDeviceDynamicRenderingLocalRead;
class FeaturePhysicalDeviceDynamicRenderingUnusedAttachmentsEXT;
class FeaturePhysicalDeviceExclusiveScissorNV;
class FeaturePhysicalDeviceExtendedDynamicState2EXT;
class FeaturePhysicalDeviceExtendedDynamicState3EXT;
class FeaturePhysicalDeviceExtendedDynamicStateEXT;
class FeaturePhysicalDeviceExtendedSparseAddressSpaceNV;
class FeaturePhysicalDeviceExternalMemoryRDMANV;
class FeaturePhysicalDeviceFaultEXT;
class FeaturePhysicalDeviceFormatPackARM;
class FeaturePhysicalDeviceFragmentDensityMap2EXT;
class FeaturePhysicalDeviceFragmentDensityMapEXT;
class FeaturePhysicalDeviceFragmentDensityMapLayeredVALVE;
class FeaturePhysicalDeviceFragmentDensityMapOffsetEXT;
class FeaturePhysicalDeviceFragmentShaderBarycentricKHR;
class FeaturePhysicalDeviceFragmentShaderInterlockEXT;
class FeaturePhysicalDeviceFragmentShadingRateEnumsNV;
class FeaturePhysicalDeviceFragmentShadingRateKHR;
class FeaturePhysicalDeviceFrameBoundaryEXT;
class FeaturePhysicalDeviceGlobalPriorityQuery;
class FeaturePhysicalDeviceGraphicsPipelineLibraryEXT;
class FeaturePhysicalDeviceHdrVividHUAWEI;
class FeaturePhysicalDeviceHostImageCopy;
class FeaturePhysicalDeviceHostQueryReset;
class FeaturePhysicalDeviceImage2DViewOf3DEXT;
class FeaturePhysicalDeviceImageAlignmentControlMESA;
class FeaturePhysicalDeviceImageCompressionControlEXT;
class FeaturePhysicalDeviceImageCompressionControlSwapchainEXT;
class FeaturePhysicalDeviceImageProcessing2QCOM;
class FeaturePhysicalDeviceImageProcessingQCOM;
class FeaturePhysicalDeviceImageRobustness;
class FeaturePhysicalDeviceImageSlicedViewOf3DEXT;
class FeaturePhysicalDeviceImageViewMinLodEXT;
class FeaturePhysicalDeviceImagelessFramebuffer;
class FeaturePhysicalDeviceIndexTypeUint8;
class FeaturePhysicalDeviceInheritedViewportScissorNV;
class FeaturePhysicalDeviceInlineUniformBlock;
class FeaturePhysicalDeviceInvocationMaskHUAWEI;
class FeaturePhysicalDeviceLegacyDitheringEXT;
class FeaturePhysicalDeviceLegacyVertexAttributesEXT;
class FeaturePhysicalDeviceLineRasterization;
class FeaturePhysicalDeviceLinearColorAttachmentNV;
class FeaturePhysicalDeviceMaintenance10KHR;
class FeaturePhysicalDeviceMaintenance4;
class FeaturePhysicalDeviceMaintenance5;
class FeaturePhysicalDeviceMaintenance6;
class FeaturePhysicalDeviceMaintenance7KHR;
class FeaturePhysicalDeviceMaintenance8KHR;
class FeaturePhysicalDeviceMaintenance9KHR;
class FeaturePhysicalDeviceMapMemoryPlacedEXT;
class FeaturePhysicalDeviceMemoryDecompressionEXT;
class FeaturePhysicalDeviceMemoryPriorityEXT;
class FeaturePhysicalDeviceMeshShaderEXT;
class FeaturePhysicalDeviceMeshShaderNV;
class FeaturePhysicalDeviceMultiDrawEXT;
class FeaturePhysicalDeviceMultisampledRenderToSingleSampledEXT;
class FeaturePhysicalDeviceMultiview;
class FeaturePhysicalDeviceMultiviewPerViewRenderAreasQCOM;
class FeaturePhysicalDeviceMultiviewPerViewViewportsQCOM;
class FeaturePhysicalDeviceMutableDescriptorTypeEXT;
class FeaturePhysicalDeviceNestedCommandBufferEXT;
class FeaturePhysicalDeviceNonSeamlessCubeMapEXT;
class FeaturePhysicalDeviceOpacityMicromapEXT;
class FeaturePhysicalDeviceOpticalFlowNV;
class FeaturePhysicalDevicePageableDeviceLocalMemoryEXT;
class FeaturePhysicalDevicePartitionedAccelerationStructureNV;
class FeaturePhysicalDevicePerStageDescriptorSetNV;
class FeaturePhysicalDevicePerformanceCountersByRegionARM;
class FeaturePhysicalDevicePerformanceQueryKHR;
class FeaturePhysicalDevicePipelineBinaryKHR;
class FeaturePhysicalDevicePipelineCacheIncrementalModeSEC;
class FeaturePhysicalDevicePipelineCreationCacheControl;
class FeaturePhysicalDevicePipelineExecutablePropertiesKHR;
class FeaturePhysicalDevicePipelineLibraryGroupHandlesEXT;
class FeaturePhysicalDevicePipelineOpacityMicromapARM;
class FeaturePhysicalDevicePipelinePropertiesEXT;
class FeaturePhysicalDevicePipelineProtectedAccess;
class FeaturePhysicalDevicePipelineRobustness;
class FeaturePhysicalDevicePresentBarrierNV;
class FeaturePhysicalDevicePresentId2KHR;
class FeaturePhysicalDevicePresentIdKHR;
class FeaturePhysicalDevicePresentModeFifoLatestReadyKHR;
class FeaturePhysicalDevicePresentTimingEXT;
class FeaturePhysicalDevicePresentWait2KHR;
class FeaturePhysicalDevicePresentWaitKHR;
class FeaturePhysicalDevicePrimitiveTopologyListRestartEXT;
class FeaturePhysicalDevicePrimitivesGeneratedQueryEXT;
class FeaturePhysicalDevicePrivateData;
class FeaturePhysicalDeviceProtectedMemory;
class FeaturePhysicalDeviceProvokingVertexEXT;
class FeaturePhysicalDeviceRGBA10X6FormatsEXT;
class FeaturePhysicalDeviceRasterizationOrderAttachmentAccessEXT;
class FeaturePhysicalDeviceRawAccessChainsNV;
class FeaturePhysicalDeviceRayQueryKHR;
class FeaturePhysicalDeviceRayTracingInvocationReorderEXT;
class FeaturePhysicalDeviceRayTracingInvocationReorderNV;
class FeaturePhysicalDeviceRayTracingLinearSweptSpheresNV;
class FeaturePhysicalDeviceRayTracingMaintenance1KHR;
class FeaturePhysicalDeviceRayTracingMotionBlurNV;
class FeaturePhysicalDeviceRayTracingPipelineKHR;
class FeaturePhysicalDeviceRayTracingPositionFetchKHR;
class FeaturePhysicalDeviceRayTracingValidationNV;
class FeaturePhysicalDeviceRelaxedLineRasterizationIMG;
class FeaturePhysicalDeviceRenderPassStripedARM;
class FeaturePhysicalDeviceRepresentativeFragmentTestNV;
class FeaturePhysicalDeviceRobustness2KHR;
class FeaturePhysicalDeviceSamplerYcbcrConversion;
class FeaturePhysicalDeviceScalarBlockLayout;
class FeaturePhysicalDeviceSchedulingControlsARM;
class FeaturePhysicalDeviceSeparateDepthStencilLayouts;
class FeaturePhysicalDeviceShader64BitIndexingEXT;
class FeaturePhysicalDeviceShaderAtomicFloat16VectorNV;
class FeaturePhysicalDeviceShaderAtomicFloat2EXT;
class FeaturePhysicalDeviceShaderAtomicFloatEXT;
class FeaturePhysicalDeviceShaderAtomicInt64;
class FeaturePhysicalDeviceShaderBfloat16KHR;
class FeaturePhysicalDeviceShaderClockKHR;
class FeaturePhysicalDeviceShaderCoreBuiltinsARM;
class FeaturePhysicalDeviceShaderDemoteToHelperInvocation;
class FeaturePhysicalDeviceShaderDrawParameters;
class FeaturePhysicalDeviceShaderEarlyAndLateFragmentTestsAMD;
class FeaturePhysicalDeviceShaderExpectAssume;
class FeaturePhysicalDeviceShaderFloat16Int8;
class FeaturePhysicalDeviceShaderFloat8EXT;
class FeaturePhysicalDeviceShaderFloatControls2;
class FeaturePhysicalDeviceShaderFmaKHR;
class FeaturePhysicalDeviceShaderImageAtomicInt64EXT;
class FeaturePhysicalDeviceShaderImageFootprintNV;
class FeaturePhysicalDeviceShaderIntegerDotProduct;
class FeaturePhysicalDeviceShaderIntegerFunctions2INTEL;
class FeaturePhysicalDeviceShaderLongVectorEXT;
class FeaturePhysicalDeviceShaderMaximalReconvergenceKHR;
class FeaturePhysicalDeviceShaderModuleIdentifierEXT;
class FeaturePhysicalDeviceShaderObjectEXT;
class FeaturePhysicalDeviceShaderQuadControlKHR;
class FeaturePhysicalDeviceShaderRelaxedExtendedInstructionKHR;
class FeaturePhysicalDeviceShaderReplicatedCompositesEXT;
class FeaturePhysicalDeviceShaderSMBuiltinsNV;
class FeaturePhysicalDeviceShaderSubgroupExtendedTypes;
class FeaturePhysicalDeviceShaderSubgroupRotate;
class FeaturePhysicalDeviceShaderSubgroupUniformControlFlowKHR;
class FeaturePhysicalDeviceShaderTerminateInvocation;
class FeaturePhysicalDeviceShaderTileImageEXT;
class FeaturePhysicalDeviceShaderUniformBufferUnsizedArrayEXT;
class FeaturePhysicalDeviceShaderUntypedPointersKHR;
class FeaturePhysicalDeviceShadingRateImageNV;
class FeaturePhysicalDeviceSubgroupSizeControl;
class FeaturePhysicalDeviceSubpassMergeFeedbackEXT;
class FeaturePhysicalDeviceSubpassShadingHUAWEI;
class FeaturePhysicalDeviceSwapchainMaintenance1KHR;
class FeaturePhysicalDeviceSynchronization2;
class FeaturePhysicalDeviceTensorARM;
class FeaturePhysicalDeviceTexelBufferAlignmentEXT;
class FeaturePhysicalDeviceTextureCompressionASTC3DEXT;
class FeaturePhysicalDeviceTextureCompressionASTCHDR;
class FeaturePhysicalDeviceTileMemoryHeapQCOM;
class FeaturePhysicalDeviceTilePropertiesQCOM;
class FeaturePhysicalDeviceTileShadingQCOM;
class FeaturePhysicalDeviceTimelineSemaphore;
class FeaturePhysicalDeviceTransformFeedbackEXT;
class FeaturePhysicalDeviceUnifiedImageLayoutsKHR;
class FeaturePhysicalDeviceUniformBufferStandardLayout;
class FeaturePhysicalDeviceVariablePointers;
class FeaturePhysicalDeviceVertexAttributeDivisor;
class FeaturePhysicalDeviceVertexAttributeRobustnessEXT;
class FeaturePhysicalDeviceVertexInputDynamicStateEXT;
class FeaturePhysicalDeviceVideoDecodeVP9KHR;
class FeaturePhysicalDeviceVideoEncodeAV1KHR;
class FeaturePhysicalDeviceVideoEncodeIntraRefreshKHR;
class FeaturePhysicalDeviceVideoEncodeQuantizationMapKHR;
class FeaturePhysicalDeviceVideoEncodeRgbConversionVALVE;
class FeaturePhysicalDeviceVideoMaintenance1KHR;
class FeaturePhysicalDeviceVideoMaintenance2KHR;
class FeaturePhysicalDeviceVulkan11;
class FeaturePhysicalDeviceVulkan12;
class FeaturePhysicalDeviceVulkan13;
class FeaturePhysicalDeviceVulkan14;
class FeaturePhysicalDeviceVulkanMemoryModel;
class FeaturePhysicalDeviceWorkgroupMemoryExplicitLayoutKHR;
class FeaturePhysicalDeviceYcbcr2Plane444FormatsEXT;
class FeaturePhysicalDeviceYcbcrDegammaQCOM;
class FeaturePhysicalDeviceYcbcrImageArraysEXT;
class FeaturePhysicalDeviceZeroInitializeDeviceMemoryEXT;
class FeaturePhysicalDeviceZeroInitializeWorkgroupMemory;

} // namespace merian
