// This file was autogenerated for Vulkan v1.4.338.
// Created: 2026-01-25 22:04:51.290136
// Do not edit manually!

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace merian {

/**
 * @brief Get the list of extension dependencies for a given extension.
 * @param name The extension name macro (e.g., VK_KHR_SWAPCHAIN_EXTENSION_NAME).
 * @param vk_api_version The Vulkan API version being used.
 * @return Vector of extension name strings that are required dependencies.
 *         Returns empty if no dependencies or if dependencies are satisfied by the API version.
 */
std::vector<const char*> get_extension_dependencies(const char* name, uint32_t vk_api_version);

} // namespace merian
