// This file was autogenerated for Vulkan v1.4.338.
// Created: 2026-01-28 21:04:23.429554
// Do not edit manually!

#pragma once

#include "vulkan/vulkan.hpp"

#include <cstdint>
#include <vector>

namespace merian {

/**
 * @brief Get the list of extension dependencies for a given extension.
 * @param name The extension name macro (e.g., VK_KHR_SWAPCHAIN_EXTENSION_NAME).
 * @param vk_api_version The Vulkan API version being used.
 * @return Vector of extension name strings that are required dependencies.
 *         Returns empty if no dependencies or if dependencies are satisfied by the API version.
 */
std::vector<const char*> get_extension_dependencies(const char* name, uint32_t vk_api_version);

/**
 * @brief For a extension, gets the new vk::StructureTypes that extend vk::VkPhysicalDeviceProperties2.
 * @param name The extension name macro.
 * @return Vector of vk::StructureType values for property structs from this extension.
 */
std::vector<vk::StructureType> get_extension_property_types(const char* name);

/**
 * @brief For a given API version, gets the new vk::StructureTypes that extend vk::VkPhysicalDeviceProperties2.
 * @param vk_api_version The Vulkan API version.
 * @return Vector of vk::StructureType values for core property structs (cumulative).
 */
std::vector<vk::StructureType> get_api_version_property_types(uint32_t vk_api_version);

} // namespace merian
