// This file was autogenerated for Vulkan v1.4.342.
// Do not edit manually!

#pragma once

#include "merian/vk/utils/vulkan_features.hpp"
#include "merian/vk/utils/vulkan_properties.hpp"

#include <cstdint>
#include <string>
#include <vector>

namespace merian {

/**
 * @brief Get list of all SPIR-V extension names.
 * @return Vector of SPIR-V extension name strings.
 */
std::vector<const char*> get_spirv_extensions();

/**
 * @brief Get Vulkan extension requirements for a SPIR-V extension.
 *
 * Returns the Vulkan extensions needed to use a SPIR-V extension.
 * If the SPIR-V extension is satisfied by the given Vulkan API version,
 * returns an empty vector.
 *
 * @param spirv_extension The SPIR-V extension name (e.g., "SPV_KHR_variable_pointers")
 * @param vk_api_version The Vulkan API version (e.g., VK_API_VERSION_1_1)
 * @return Vector of required Vulkan extension name macros, or empty if satisfied by version
 */
std::vector<const char*> get_spirv_extension_requirements(
    const char* spirv_extension,
    uint32_t vk_api_version);

/**
 * @brief Get list of all SPIR-V capability names.
 * @return Vector of SPIR-V capability name strings.
 */
std::vector<const char*> get_spirv_capabilities();

/**
 * @brief Check if a SPIR-V capability is supported.
 *
 * Checks if any of the enable conditions for the capability are satisfied.
 * This includes checking version requirements, features, and properties.
 *
 * @param capability The SPIR-V capability name (e.g., "Geometry")
 * @param vk_api_version The Vulkan API version
 * @param features The device features
 * @param properties The device properties
 * @return true if the capability is supported
 */
bool is_spirv_capability_supported(
    const char* capability,
    uint32_t vk_api_version,
    const VulkanFeatures& features,
    const VulkanProperties& properties);

/**
 * @brief Get Vulkan extensions required for a SPIR-V capability.
 *
 * Returns extensions from enable conditions that are not satisfied by
 * the given Vulkan API version.
 *
 * @param capability The SPIR-V capability name
 * @param vk_api_version The Vulkan API version
 * @return Vector of required Vulkan extension name macros
 */
std::vector<const char*> get_spirv_capability_extensions(
    const char* capability,
    uint32_t vk_api_version);

/**
 * @brief Get features required for a SPIR-V capability.
 *
 * Returns feature requirements as "structShortName/featureName" strings
 * that can be passed directly to VulkanFeatures::enable_features().
 *
 * @param capability The SPIR-V capability name
 * @param vk_api_version The Vulkan API version
 * @return Vector of feature strings in "structName/featureName" format
 */
std::vector<std::string> get_spirv_capability_features(
    const char* capability,
    uint32_t vk_api_version);

} // namespace merian
